### ISSUE TITLE
make is broken -- ack/develop 3cbef8e35a0149376a12f0f137345db29e1caca1

### ISSUE THREAD

**Issue by NorthWindH** [gladiusjs/gladius-core#67]
### Steps to reproduce (bash):

$ make clean
$ make
Creating ./dist
Building ./dist/gladius.js

Tracing dependencies for: ../tools/almond

node.js:208
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Error: Error evaluating module "undefined" at location "c:/Users/Hasan/Misc/Repos/Gladius/src/../external/CubicVR.js/dist/CubicVR.js":
Error: ENOENT, The operation completed successfully.
 'c:/Users/Hasan/Misc/Repos/Gladius/src/../external/CubicVR.js/dist/CubicVR.js'
fileName:c:/Users/Hasan/Misc/Repos/Gladius/src/../external/CubicVR.js/dist/CubicVR.js
lineNumber: undefined
http://requirejs.org/docs/errors.html#defineerror
In module tree:
    gladius-src
      graphics/service

```
at Function.onError (c:\Users\Hasan\Misc\Repos\Gladius\tools\r.js:7355:23)
at execManager (c:\Users\Hasan\Misc\Repos\Gladius\tools\r.js:704:28)
at Object.onDep (c:\Users\Hasan\Misc\Repos\Gladius\tools\r.js:745:33)
at execManager (c:\Users\Hasan\Misc\Repos\Gladius\tools\r.js:713:45)
at Object.onDep (c:\Users\Hasan\Misc\Repos\Gladius\tools\r.js:745:33)
at execManager (c:\Users\Hasan\Misc\Repos\Gladius\tools\r.js:713:45)
at Object.onDep (c:\Users\Hasan\Misc\Repos\Gladius\tools\r.js:745:33)
at execManager (c:\Users\Hasan\Misc\Repos\Gladius\tools\r.js:713:45)
at Object.onDep (c:\Users\Hasan\Misc\Repos\Gladius\tools\r.js:745:33)
at execManager (c:\Users\Hasan\Misc\Repos\Gladius\tools\r.js:713:45)
```

make: **\* [dist/gladius.js] Error 1

$

**Comment by NorthWindH** [comment]
@AlanKligman you have been notified good sir :)

**Comment by modeswitch** [comment]
Fixed in my work branch.

**Comment by modeswitch** [comment]
Fixed in develop.
